### ISSUE TITLE
sys/io.h does not exist on arm64 arch

### ISSUE THREAD

**Issue by jmeloranta** [n4ogw/so2sdr#5]
In order to compile on arm64 Debian (Raspberry Pi 4), I had to remove the following include line in so2sdr/linux_pp.h:
#include <sys/io.h>

This include file does not exist on arm64 architecture (only intel, arm32, alpha etc). After commenting out the above line, everything compiles OK. So, likely it can be removed altogether.

**Comment by n4ogw** [comment]
Thanks for the comment- I have never tried to build so2sdr on a Pi. You are correct, that include is not needed; I have removed it.
Tor N4OGW

    On Wednesday, December 8, 2021, 11:27:50 PM CST, Jussi Eloranta ***@***.***> wrote:  
 
 


In order to compile on arm64 Debian (Raspberry Pi 4), I had to remove the following include line in so2sdr/linux_pp.h:
#include <sys/io.h>

This include file does not exist on arm64 architecture (only intel, arm32, alpha etc). After commenting out the above line, everything compiles OK. So, likely it can be removed altogether.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
